name: test
on:
  pull_request:
  push:
    paths:
      - "**.go"
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            .github/workflows/test.yaml
      - name: Run Go Tests
        if: env.GIT_DIFF
        run: |
          go test -cover -race -timeout=2m ./...
